// Flat config generated by the @nuxt/eslint module (Vue + TS + Nuxt aware).
// Project rules go in the second argument to withNuxt().
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    // handoff reference files (prototype) — not project source
    ignores: ['docs/**'],
  },
  {
    rules: {
      // icon paths are static and trusted (PsIcon) — v-html is safe here
      'vue/no-v-html': 'off',
    },
  },
)
