// Flat config generated by the @nuxt/eslint module (Vue + TS + Nuxt aware).
// Project rules go in the second argument to withNuxt().
import withNuxt from './.nuxt/eslint.config.mjs'
// Desliga regras de formatação que conflitam com o Prettier (ex.: vue/html-self-closing).
// Deve vir por último para sobrescrever as regras anteriores.
import eslintConfigPrettier from 'eslint-config-prettier'

export default withNuxt(
  {
    // handoff reference files (prototype) — not project source
    ignores: ['docs/**'],
  },
  {
    rules: {
      // icon paths are static and trusted (PsIcon) — v-html is safe here
      'vue/no-v-html': 'off',
    },
  },
  eslintConfigPrettier,
)
